### ISSUE TITLE
tempfiles are not removed after running ostir

### ISSUE THREAD

**Issue by jhahnfeld** [barricklab/ostir#5]
Hi,

the tempfiles created in [ViennaRNA.py](https://github.com/barricklab/ostir/blob/33b1e55b7b787f9d187cbf877b5194a5be9d9156/ostir/ViennaRNA.py#L46) are not deleted after running ostir.
They should be deleted automatically after a successful or failed run to avoid filling up the /temp directory.

Best regards

Julian

**Comment by croots** [comment]
Hi Julian,

Thanks for the report! This should be fixed with the latest commit (10ef1b14be9a4854392fc81121eb6171a7b15d8b). Due to python limitations this should work as long as the python interpreter terminates normally - this won't delete files if the OS terminates the interpreter with a userinterupt or through other means like terminating python.

>  They should be deleted automatically after a successful or _failed run_ to avoid filling up the /temp directory.

For clarification, is the failed run you're referring to just not finding any valid RBS's or is OSTIR terminating with an error?

Cameron

**Comment by jhahnfeld** [comment]
Hi Cameron,

> For clarification, is the failed run you're referring to just not finding any valid RBS's or is OSTIR terminating with an error?

I just wanted to point out that the tmpfiles would remain regardless of the exit status. 

In my test, the last commit did not completely resolve the issue. The tmpfiles are removed after the Python interpreter exits, but they persist even though the `run_ostir()` function imported via `from ostir.ostir import run_ostir` has finished its run and the script continues to run other functions.

My problem is that I that I have ~ 1 Mio. separate sequences I want to examine and for each one a `run_ostir()` call is executed. Since I am using a cluster with shared resources, the tmpfiles fill the /tmp/ directory as long as the python script is running, which causes problems.

Is it possible to remove the tmpfiles directly after the `run_ostir()` function has finished?

Julian

**Comment by croots** [comment]
Hi Julian,

Thanks - that makes sense, especially if you're running everything in a single python script. I added some an additional check during garbage collection, so temp files should be removed as soon as the OSTIRFactory objects get destroyed. Assuming my understanding of python garbage collection is right it shouldn't be necessary; however, if I'm wrong and you're using the script I provided in #4 you may need to add `del CalcObj` to the end of that version of `run_ostir()`.

In later versions of OSTIR I'd like to make such that the temp files aren't created at all by using ViennaRNA's python module.

As a note, my original implementation that clears temp files uses the `atexit` module. I didn't remove this because it makes sense to keep it as a precaution in case the script does actually error out. Since you're running a million sequences here, you might have to call `atexit.unregister(ostir.ViennaRNA.clean_temp_file)` between sequences to keep memory usage down.

**Comment by jhahnfeld** [comment]
Hi Cameron,

I checked the latest commit (d3221db4ce47bbe8b9584396f325da6ca7c07374) with my script and the tempfiles are now removed after the `run_ostir()` function completes.

This resolves the issue. Will you make a point release with the fix?

Julian

**Comment by croots** [comment]
Hi @jhahnfeld 

See #7 and release Version 1.1.0. OSTIR should no longer need to generate any tempfiles and is much faster.

**Comment by jhahnfeld** [comment]
Hi @croots,

thank you very much for the update.
I have tested the new OSTIR release and the tempfiles problem is now solved.
